import numpy as np
import os
import json

# get the directory where the py file is located
dir = os.path.dirname(os.path.realpath(__file__))
os.chdir(dir)

with open('structure.as', 'r') as f:
    I = f.readlines()

# Determine whether the file folder exists
if not os.path.exists('vaspfiles'):

    # make a new directory in the current directory
    os.mkdir(dir + '/vaspfiles')

    # set the work path as the new directory
    os.chdir(dir + '/vaspfiles')
else:
    os.chdir(dir + '/vaspfiles')


def tran(fix):
    if fix == 'T':
        return 'F'
    else:
        return 'T'


with open('POSCAR', 'w') as f:
    f.write('POSCAR generated by tran_as_POSCAR.py\n')
    f.write('1.0\n')
    len_I = len(I)

    for i in range(len_I):
        if 'atoms' in I[i]:
            a_tot = float(I[i+1].split()[0])
        if 'Lattice' in I[i]:
            al = I[i+1].split()
            al = ['%.16f' % float(x) for x in al[0:3]]
            bl = I[i+2].split()
            bl = ['%.16f' % float(x) for x in bl[0:3]]
            cl = I[i+3].split()
            cl = ['%.16f' % float(x) for x in cl[0:3]]
        if 'Cartesian' in I[i]:
            if 'Fix' in I[i]:
                # It = I[i].split()
                pos = {'atom': [], 'cart': [], 'Fix': []}
                for j in range(i+1, i+1+int(a_tot)):
                    Ic = I[j].split()
                    pos['atom'].append(Ic[0])
                    pos['cart'].append(['%.16f' % float(x) for x in Ic[1:4]])
                    pos['Fix'].append([tran(x) for x in Ic[4:7]])
            else:
                pos = {'atom': [], 'cart': []}
                for j in range(i+1, i+1+int(a_tot)):
                    Ic = I[j].split()
                    pos['atom'].append(Ic[0])
                    pos['cart'].append(['%.16f' % float(x) for x in Ic[1:4]])

    f.write('%+22s' % al[0]+'%+22s' % al[1]+'%+22s' % al[2]+'\n')
    f.write('%+22s' % bl[0]+'%+22s' % bl[1]+'%+22s' % bl[2]+'\n')
    f.write('%+22s' % cl[0]+'%+22s' % cl[1]+'%+22s' % cl[2]+'\n')

    # Count the number of atoms in the order of 'pos' list
    atom_num = {}
    for i in pos['atom']:
        if i in atom_num:
            atom_num[i] += 1
        else:
            atom_num[i] = 1
    list_atom = list(atom_num.keys())
    list_atom_value = list(atom_num.values())
    for i in list_atom:
        f.write('%+5s' % i)
    f.write('\n')
    for i in list_atom_value:
        f.write('%+6s' % i)
    f.write('\n')
    f.write('''Selective dynamics
Cartesian
''')
    if 'Fix' in pos:
        for i in range(len(pos['atom'])):
            f.write('%+20s' % pos['cart'][i][0]+'%+20s' % pos['cart'][i][1]+'%+20s' % pos['cart'][i]
                    [2]+'%+4s' % pos['Fix'][i][0]+'%+4s' % pos['Fix'][i][1]+'%+4s' % pos['Fix'][i][2]+'\n')
    else:
        for i in range(len(pos['atom'])):
            f.write('%+20s' % pos['cart'][i][0]+'%+20s' % pos['cart'][i][1]+'%+20s' % pos['cart'][i][2]+'\n')


'''看看 al bl cl 是数字还是字符串'''

'''接下来的思路是将分数坐标轴以及原子的坐标全部转化为变量, 然后将变量写入到POSCAR文件中'''
